import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import InputBox from '@/components/InputBox'
import Div from '@/components/Div'
import Typhography from '@/components/Typhography'
const inter = Inter({ subsets: ['latin'] })
import { FaEnvelope, FaUserAlt, FaKey, FaPhoneAlt, FaShoppingBasket } from 'react-icons/fa';
import { VscEyeClosed, VscEye } from 'react-icons/vsc';

import Button from '@/components/Button'
import Link from 'next/link'


export default function Otp() {
    return (
        <>
            <Head>
                <title>OTP Verification</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className={styles.main}>
                <Div className="flex flex-col">
                    <Div className={styles.card}>
                        <Typhography as="h1" className="text-3xl font-bold underline mb-2">OTP Verification</Typhography>
                        <Typhography as='small' className='heading text-[#f3f4ff] text-xl font-medium opacity-50'>Enter the code sent to your phone number.</Typhography>

                        <Div className="otp flex mt-5 gap-5 mb-5">
                            <InputBox name='registerPhone' className='placeholder:text-slate-400 placeholder:text-lg block bg-white w-[70px] border border-slate-300 font-semibold text-[#11175D] rounded-md p-4 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 text-center text-2xl' type='text' placeholder='0' maxlength="1" />
                            <InputBox name='registerPhone' className='placeholder:text-slate-400 placeholder:text-lg block bg-white w-[70px] border border-slate-300 font-semibold text-[#11175D] rounded-md p-4 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 text-center text-2xl' type='text' placeholder='0' maxlength="1" />
                            <InputBox name='registerPhone' className='placeholder:text-slate-400 placeholder:text-lg block bg-white w-[70px] border border-slate-300 font-semibold text-[#11175D] rounded-md p-4 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 text-center text-2xl' type='text' placeholder='0' maxlength="1" />
                            <InputBox name='registerPhone' className='placeholder:text-slate-400 placeholder:text-lg block bg-white w-[70px] border border-slate-300 font-semibold text-[#11175D] rounded-md p-4 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 text-center text-2xl' type='text' placeholder='0' maxlength="1" />
                            <InputBox name='registerPhone' className='placeholder:text-slate-400 placeholder:text-lg block bg-white w-[70px] border border-slate-300 font-semibold text-[#11175D] rounded-md p-4 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 text-center text-2xl' type='text' placeholder='0' maxlength="1" />
                            <InputBox name='registerPhone' className='placeholder:text-slate-400 placeholder:text-lg block bg-white w-[70px] border border-slate-300 font-semibold text-[#11175D] rounded-md p-4 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 text-center text-2xl' type='text' placeholder='0' maxlength="1" />
                        </Div>
                        <Div className="flex gap-3">
                            <Button className='bg-[#086FA4] w-full text-white rounded-md py-4 text-xl mb-5'>Verify OTP</Button>
                            <Button className='bg-[#edf9ff] w-full text-[#086FA4] rounded-md py-4 text-xl mb-5'>Cancle</Button>
                        </Div>


                        <Typhography as='small' className='heading text-[#e2e4ff] text-lg font-regular mb-16 mt-5'>
                            Already have an account?
                            <Link href="/login" className='text-white underline font-bold ml-2'>Login</Link>
                        </Typhography>
                    </Div>


                </Div>
            </main>
        </>
    )
}
